from all_contacts import *
import os

#print os.getcwd()

# os.chdir("/Users/Chris/GitHub/thesis/antibodies/D206/2M2D")
# bulkAllContacts("D206m2d", ['O', 'R', 'T'], 8, normalized=False)
# os.chdir("/Users/Chris/GitHub/thesis/antibodies/D206/2M9D")
# bulkAllContacts("D206m9d", ['O', 'R', 'T'], 8, normalized=False)
# os.chdir("/Users/Chris/GitHub/thesis/antibodies/D206/2MRD")
# bulkAllContacts("D206mRd", ['O', 'R', 'T'], 8, normalized=False)
# os.chdir("/Users/Chris/GitHub/thesis/antibodies/D206/MR_m165")
# bulkAllContacts("D206mut165d", ['O', 'R', 'T'], 8, normalized=False)
# os.chdir("/Users/Chris/GitHub/thesis/antibodies/D206/MR_m390")
# bulkAllContacts("D206mut390d", ['O', 'R', 'T'], 8, normalized=False)
# os.chdir("/Users/Chris/GitHub/thesis/antibodies/D206/MR_m435")
# bulkAllContacts("D206mut435d", ['O', 'R', 'T'], 8, normalized=False)

# os.chdir("/Users/Chris/GitHub/thesis/antibodies/D430/2M7D")
# bulkAllContacts("D430m7d", ['O', 'R', 'T'], 8, normalized=False)
# os.chdir("/Users/Chris/GitHub/thesis/antibodies/D430/2M8D")
# bulkAllContacts("D430m8d", ['O', 'R', 'T'], 8, normalized=False)
# os.chdir("/Users/Chris/GitHub/thesis/antibodies/D430/2MRD")
# bulkAllContacts("D430mRd", ['O', 'R', 'T'], 8, normalized=False)
# os.chdir("/Users/Chris/GitHub/thesis/antibodies/D410/MR_m165")
# bulkAllContacts("D410mut165d", ['O', 'R', 'T'], 8, normalized=False)
# os.chdir("/Users/Chris/GitHub/thesis/antibodies/D410/MR_m390")
# bulkAllContacts("D410mut390d", ['O', 'R', 'T'], 8, normalized=False)
# os.chdir("/Users/Chris/GitHub/thesis/antibodies/D410/MR_m435")
# bulkAllContacts("D410mut435d", ['O', 'R', 'T'], 8, normalized=False)

# os.chdir("/Users/Chris/GitHub/thesis/antibodies/D410/2M1D")
# bulkAllContacts("D410m1d", ['O', 'R', 'T'], 8, normalized=False)
# os.chdir("/Users/Chris/GitHub/thesis/antibodies/D410/2M5D")
# bulkAllContacts("D410m5d", ['O', 'R', 'T'], 8, normalized=False)
# os.chdir("/Users/Chris/GitHub/thesis/antibodies/D410/2MRD")
# bulkAllContacts("D410mRd", ['O', 'R', 'T'], 8, normalized=False)
os.chdir("/Users/Chris/GitHub/thesis/antibodies/D430/MR_m165")
bulkAllContacts("D430mut165d", ['O', 'R', 'T'], 8, normalized=False)
os.chdir("/Users/Chris/GitHub/thesis/antibodies/D430/MR_m390")
bulkAllContacts("D430mut390d", ['O', 'R', 'T'], 8, normalized=False)
os.chdir("/Users/Chris/GitHub/thesis/antibodies/D430/MR_m435")
bulkAllContacts("D430mut435d", ['O', 'R', 'T'], 8, normalized=False)